class Product_Modal {
  int? id;
  String? title, description, category, image;
  double? price;
  Rating? rating;

//
  Product_Modal({
    this.id,
    this.title,
    this.description,
    this.category,
    this.image,
    this.price,
    this.rating,
  });

// convert to factory   ////
  Product_Modal product(Map m1) {
    id = m1['id'];
    title = m1['title'];
    description = m1['description'];
    category = m1['category'];
    image = m1['image'];
    price = m1['price'];
    rating = Rating().factory(m1);

    Product_Modal P2 = Product_Modal(
        id: id,
        title: title,
        description: description,
        category: category,
        image: image,
        price: price,
        rating: rating);
    return P2;
  }
}

class Rating {
  double? rate;
  int? count;

  Rating({
    this.rate,
    this.count,
  });

  Rating factory(Map m1) {
    rate = m1['rate'];
    count = m1['count'];

    Rating p1 = Rating(
      rate: rate,
      count: count,
    );
    return p1;
  }
}

//****************************************************************************/
// class Autogenerated {
//   int? id;
//   String? title;
//   double? price;
//   String? description;
//   String? category;
//   String? image;
//   Rating? rating;
//
//   Autogenerated(
//       {this.id,
//         this.title,
//         this.price,
//         this.description,
//         this.category,
//         this.image,
//         this.rating});
//
//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     title = json['title'];
//     price = json['price'];
//     description = json['description'];
//     category = json['category'];
//     image = json['image'];
//     rating =
//     json['rating'] != null ? new Rating.fromJson(json['rating']) : null;
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['title'] = this.title;
//     data['price'] = this.price;
//     data['description'] = this.description;
//     data['category'] = this.category;
//     data['image'] = this.image;
//     if (this.rating != null) {
//       data['rating'] = this.rating!.toJson();
//     }
//     return data;
//   }
// }
//
// class Rating {
//   double? rate;
//   int? count;
//
//   Rating({this.rate, this.count});
//
//   Rating.fromJson(Map<String, dynamic> json) {
//     rate = json['rate'];
//     count = json['count'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['rate'] = this.rate;
//     data['count'] = this.count;
//     return data;
//   }
// }
